package com.keltruc.mymemos.data.crypto

import android.util.Log
import androidx.test.ext.junit.runners.AndroidJUnit4
import com.keltruc.mymemos.data.export.BackupCrypto
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith
import java.io.ByteArrayInputStream
import java.io.ByteArrayOutputStream
import java.util.Base64
import javax.crypto.SecretKeyFactory
import javax.crypto.spec.PBEKeySpec

/**
 * Closes the one question the Phase 0 crypto spike could not answer on a laptop.
 *
 * The spike proved that SunJCE and CryptoKit derive the same key and produce the same
 * bytes, unicode and emoji passwords included. Android does not use SunJCE: it resolves
 * `PBKDF2WithHmacSHA256` through its own provider, and providers have historically
 * disagreed about how to turn a `char[]` password into bytes, some using UTF-8 and some
 * Latin-1. A disagreement would mean a memo locked on a phone could not be opened on a
 * Mac, but only for people whose password is not plain ASCII, which is exactly the kind of
 * bug that ships.
 *
 * The vectors below were generated by `VectorGen.java` in the MyMemos-spikes repository
 * and are already known to match CryptoKit. If this test passes, all three platforms
 * agree.
 */
@RunWith(AndroidJUnit4::class)
class AndroidCryptoParityTest {

    private data class Vector(
        val label: String,
        val password: String,
        val plaintext: String,
        val iterations: Int,
        val keyB64: String,
        val stored: String,
    )

    /** Fixed so the derivation is reproducible: salt is 1..16, nonce is 0xA0..0xAB. */
    private val salt = ByteArray(16) { (it + 1).toByte() }

    private val vectors = listOf(
        Vector(
            label = "ascii-memo",
            password = "correct horse battery staple",
            plaintext = "Buy milk\n- [ ] and bread",
            iterations = 120_000,
            keyB64 = "JeNJk1h5jkVgUUBOi5gUMUPdrBNznUvI5yYGmN+RJt0=",
            stored = "mymemos-enc:v1:AQIDBAUGBwgJCgsMDQ4PEKChoqOkpaanqKmqq29bkoi8l+FkS2XERnV4kkrTYx4k4fD+nNxMT9ESweUapFOGKQcFKI8=",
        ),
        Vector(
            // The case that would actually break: German, French and Chinese characters.
            label = "unicode-password",
            password = "paßwort-éè-你好",
            plaintext = "Locked note",
            iterations = 120_000,
            keyB64 = "lWcs/VFNG2q04v9omNLLjix1FhMhQ1wSePjBFHzx8rQ=",
            stored = "mymemos-enc:v1:AQIDBAUGBwgJCgsMDQ4PEKChoqOkpaanqKmqq/0VtW7MkAnwZgWbQqingx07qE4jF/MCe9E6PQ==",
        ),
        Vector(
            label = "emoji-password",
            password = "keys🔑🔐",
            plaintext = "Tagged £ and €",
            iterations = 120_000,
            keyB64 = "a5z4zflboeO4CUinf+PtVRteBrIVOW8hoOvTrSQUnpY=",
            stored = "mymemos-enc:v1:AQIDBAUGBwgJCgsMDQ4PEKChoqOkpaanqKmqqw01rymXqnZXjy4R22N3RgU/cblMDx17Sn6VvUoSidnb1Q==",
        ),
        Vector(
            label = "empty-plaintext",
            password = "short",
            plaintext = "",
            iterations = 120_000,
            keyB64 = "HSynyoeUULomZgZTT25Bc404u+QsYWZevFgNYOk4UzA=",
            stored = "mymemos-enc:v1:AQIDBAUGBwgJCgsMDQ4PEKChoqOkpaanqKmqq7hQMwmy37mULbhpcQgoS4g=",
        ),
        Vector(
            // BackupCrypto's rounds rather than MemoCipher's, so the backup format is covered too.
            label = "backup-rounds",
            password = "backup password",
            plaintext = "zip bytes stand in",
            iterations = 200_000,
            keyB64 = "NaGhOkAayhEqsaDAr9uioa1kuFg65vqJ1wVYoIltkno=",
            stored = "mymemos-enc:v1:AQIDBAUGBwgJCgsMDQ4PEKChoqOkpaanqKmqq6Ia4OtnwcOSAWMfEC1XkSqf1VsanO25LAiCPFIjiMNuuq4=",
        ),
    )

    private fun deriveKey(password: CharArray, iterations: Int): ByteArray =
        SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256")
            .generateSecret(PBEKeySpec(password, salt, iterations, 256)).encoded

    @Test
    fun androidDerivesTheSameKeysAsTheJvmAndCryptoKit() {
        val provider = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256").provider
        Log.i(TAG, "PBKDF2WithHmacSHA256 provider on this device: ${provider.name} ${provider.version}")

        val mismatches = vectors.mapNotNull { v ->
            val actual = Base64.getEncoder().encodeToString(deriveKey(v.password.toCharArray(), v.iterations))
            if (actual == v.keyB64) null else "${v.label}: expected ${v.keyB64} but this device derived $actual"
        }
        assertTrue(
            "Android's provider (${provider.name}) disagrees with SunJCE and CryptoKit:\n" +
                mismatches.joinToString("\n"),
            mismatches.isEmpty(),
        )
    }

    @Test
    fun memoCipherOpensBlobsSealedOnAnotherPlatform() {
        vectors.filter { it.iterations == 120_000 }.forEach { v ->
            val opened = MemoCipher.decrypt(v.stored, v.password.toCharArray())
            assertEquals("${v.label} did not decrypt to the expected text", v.plaintext, opened)
        }
    }

    @Test
    fun theWrongPasswordIsRejectedRatherThanReturningRubbish() {
        val v = vectors.first()
        try {
            MemoCipher.decrypt(v.stored, (v.password + "x").toCharArray())
            throw AssertionError("a wrong password was accepted")
        } catch (expected: MemoCipher.WrongPassword) {
            // what should happen
        }
    }

    @Test
    fun backupCryptoRoundTripsWithANonAsciiPassword() {
        val password = "paßwort-éè-你好".toCharArray()
        val payload = "a stand-in for the backup zip, with a £ in it".toByteArray()

        val sealed = ByteArrayOutputStream()
        BackupCrypto.encrypting(sealed, password.copyOf()).use { it.write(payload) }

        val opened = BackupCrypto.decrypting(ByteArrayInputStream(sealed.toByteArray()), password.copyOf())
            .use { it.readBytes() }

        assertEquals(String(payload), String(opened))
    }

    /**
     * Seals the same plaintexts on this device with fresh random salts and nonces so the JVM
     * and Swift verifiers can prove the other direction. Logged rather than written to a
     * file: a library module's test APK is self-instrumenting and is uninstalled when the
     * run finishes, taking its files with it. Nothing secret is logged, since these are test
     * vectors whose passwords are in the source above.
     *
     * Collect them with:
     *     adb logcat -d -s AndroidCryptoParity | sed -n 's/.*VECTOR //p'
     */
    @Test
    fun logsFreshBlobsForTheOtherPlatformsToVerify() {
        val encoder = Base64.getEncoder()
        vectors.filter { it.iterations == 120_000 }.forEach { v ->
            val stored = MemoCipher.encrypt(v.plaintext, v.password.toCharArray())
            // Round-trip on this device first, so a broken vector fails here and not later.
            assertEquals(v.plaintext, MemoCipher.decrypt(stored, v.password.toCharArray()))
            val line = listOf(
                v.label,
                encoder.encodeToString(v.password.toByteArray()),
                encoder.encodeToString(v.plaintext.toByteArray()),
                v.iterations.toString(),
                stored,
            ).joinToString("\t")
            Log.i(TAG, "VECTOR $line")
        }
    }

    private companion object {
        const val TAG = "AndroidCryptoParity"
    }
}
